### ISSUE TITLE
Crash: module time has no attribute clock

### ISSUE THREAD

**Issue by vimpostor** [whentze/loltanks#4]
```
Traceback (most recent call last):
  File "/tmp/loltanks/loltanks.py", line 146, in <module>
    curses.wrapper(main)
  File "/usr/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/tmp/loltanks/loltanks.py", line 66, in main
    gamestep(screen, mainwin, statuswin, p, world, conf, n_turns)
  File "/tmp/loltanks/loltanks.py", line 90, in gamestep
    t_begin = time.clock()
AttributeError: module 'time' has no attribute 'clock'
```

**Comment by vimpostor** [comment]
Hi @whentze, it looks like time.clock() got deprecated. The following patch fixes the issue. Feel free to apply it (`perf_counter()` measures wall-clock time):

[0001-Use-perf_counter-instead-of-clock.patch.txt](https://github.com/whentze/loltanks/files/7041422/0001-Use-perf_counter-instead-of-clock.patch.txt)


```diff
diff --git a/loltanks.py b/loltanks.py
index 6a6a6c8..8859f90 100755
--- a/loltanks.py
+++ b/loltanks.py
@@ -87,7 +87,7 @@ def gameover(screen, winner):
   return

 def gamestep(screen, mainwin, statuswin, currentplayer, world, conf, n_turns):
-  t_begin = time.clock()
+  t_begin = time.perf_counter()
   h, w = mainwin.getmaxyx()
   mainwin.erase()
   statuswin.erase()
@@ -138,7 +138,7 @@ def gamestep(screen, mainwin, statuswin, currentplayer, world, conf, n_turns):

   mainwin.refresh()
   statuswin.refresh()
-  t_end = time.clock()
+  t_end = time.perf_counter()
   if(t_end < t_begin + 0.02):
     time.sleep(t_begin + 0.02 - t_end)
```
